#:kivy 2.0

<MainScreenManager>:
    WelcomeScreen:
        name: 'WelcomeScreen'
    LoginScreen:
        name: 'LoginScreen'
    SignUpScreen:
        name: 'SignUpScreen'
    SignUpScreen2a:
        name: 'SignUpScreen2a'
    SignUpScreen2b:
        name: 'SignUpScreen2b'
    SignUpScreen3:
        name: 'SignUpScreen3'
    SignUpScreen4:
        name: 'SignUpScreen4'
    ProfileScreen:
        name: 'ProfileScreen'