#:kivy 2.0
<MyScreen>
    MDIconButton:
        icon: "language-python"
        user_font_size: "64sp"
        pos_hint:{'center_x':0.5, 'center_y': 0.6}
        on_release:
            root.manager.transition.direction = 'right'
            app.change_screen('RootScreen')
            

    MDLabel:
        pos_hint: {'center_x':0.5, 'center_y':0.5}
        halign: 'center'
        text:'Olá essa é a tela de Login!'
        bold: True